module.exports = 
  id:"int"
  md:"text"
  html:"text"
  time:"datetime"
  user_id:"int"
  user_headpic:"varchar(255)"
  user_nick:"varchar(50)"
  target_id:"varchar(100)"
  parent_id:"int"
  recomment_count:"int"
